---

- name: Install PostgrSQL
  apt:
    pkg:
    - postgresql-{{ db.ver }}
    - postgresql-contrib-{{ db.ver }}

- name: Install python3 and ower pkg
  apt:
    pkg:
    - python3-pip
    - python3-dev
    - libpq-dev
    - acl

- name: Install python lib
  pip:
    name: psycopg2
    state: present

- name: Start and Disable PostgreSQL server
  systemd:
    name: postgresql.service
    enabled: no
    state: started

- name: PostgreSQL listen addresses
  shell: sed -i.bak "s/#listen_addresses = 'localhost'/listen_addresses = '{{ ansible_facts.tun0.ipv4.address }}, 127.0.0.1'/g" /etc/postgresql/{{ db.ver }}/main/postgresql.conf
  notify:
    handler_restart_postgresql

- name: Configure Zabbix db 
  import_tasks: zabbix.yml

- name: Configure Roundcube db
  import_tasks: roundcube.yml

- name: Configure Wordpress db 
  import_tasks: wordpress.yml

- name: Configure DEMO db
  import_tasks: demo.yml

- name: Configure PostgreSQL monitoring user
  import_tasks: pgmonitoring.yml
