---

- name: Install PostgrSQL
  apt:
    pkg:
    - postgresql-{{ db.ver }}
    - postgresql-contrib-{{ db.ver }}

- name: Install python3 and ower pkg
  apt:
    pkg:
    - python3-pip
    - python3-dev
    - libpq-dev
    - acl

- name: Install python lib
  pip:
    name: psycopg2
    state: present

- name: Start and Disable PostgreSQL server
  systemd:
    name: postgresql.service
    enabled: no
    state: started

- name: PostgreSQL listen addresses
  shell: sed -i.bak "s/#listen_addresses = 'localhost'/listen_addresses = '{{ ansible_facts.tun0.ipv4.address }}, 127.0.0.1'/g" /etc/postgresql/{{ db.ver }}/main/postgresql.conf
  notify:
    handler_restart_postgresql

- name: Setting permissions
  shell: chown -R postgres:mk-ansible /share/pg

- name: Upload dump
  become: yes
  become_user: postgres
  shell: psql -f /share/pg/dumpfile postgres

- name: Users. Add rule
  postgresql_pg_hba:
    dest: /etc/postgresql/{{ db.ver }}/main/pg_hba.conf
    contype: host
    users: "{{ item.users }}"
    databases: "{{ item.databases }}"
    source: "{{ vpn.gate }}/{{ vpn.prefix }}"
    method: md5
  with_items:
  - {users: '{{ zabbix.db_user }}',databases: '{{ zabbix.db_name }}'}
  - {users: '{{ wp.db_user }}',databases: '{{ wp.db_name }}'}
  - {users: '{{ roundcube.db_user }}',databases: '{{ roundcube.db_name }}'}
  - {users: '{{ demo.db_user }}',databases: '{{ demo.db_name1 }}'}
  - {users: '{{ demo.db_user }}',databases: '{{ demo.db_name2 }}'} 
  notify:
    handler_restart_postgresql

- name: Monitoring. Add rule
  postgresql_pg_hba:
    dest: /etc/postgresql/{{ db.ver }}/main/pg_hba.conf
    contype: host
    users: "{{ zabbix.monidoring.db_user }}"
    databases: "{{ zabbix.db_name }}"
    source: 127.0.0.1/8
    method: md5
  notify:
    handler_restart_postgresql 
