---

- name: Configure monitoring user 
  become: yes
  become_user: postgres
  block:
    - name: Create user
      postgresql_user:
        db: "{{ zabbix.db_name }}"
        name: "{{ zabbix.monidoring.db_name }}"
        password: "{{ zabbix.monidoring.db_pass }}"
        priv: "ALL"
        #role_attr_flags: SUPERUSER

- name: Add rule
  postgresql_pg_hba:
    dest: /etc/postgresql/{{ db.ver }}/main/pg_hba.conf
    contype: host
    users: "{{ zabbix.db_user }}"
    databases: "{{ zabbix.db_name }}"
    source: 127.0.0.1/8 
    method: md5
  notify:
    handler_restart_postgresql
