---

- name: php - install PHP
  apt:
    pkg:
    - php
    - php-auth-sasl
    - php-bcmath
    - php-cli
    - php-common
    - php-curl
    - php-gd
    - php-getid3
    - php-imagick
    - php-intl
    - php-json
    - php-ldap
    - php-mail-mime
    - php-masterminds-html5
    - php-mbstring
    - php-opcache
    - php-net-sieve
    - php-net-smtp
    - php-net-socket
    - php-pear
    - php-pgsql
    - php-pspell
    - php-readline
    - php-soap
    - php-xml
    - php-xmlrpc
    - php-zip

- name: php - add pgsql extension
  replace:
    path: /etc/php/8.1/apache2/php.ini
    regexp: '^;extension=pgsql$'
    replace: 'extension=pgsql'
    backup: yes

- name: php - set php timezone
  lineinfile:
    path: /etc/php/8.1/apache2/php.ini
    regexp: '^;date.timezone = '
    line: 'date.timezone = "Europe/Moscow"'
