---

- name: db - create user
  postgresql_user:
    name: "{{ db.cms.user }}"
    password: "{{ db.cms.pass }}"
  no_log: true

- name: db - create db
  postgresql_db:
    name: "{{ db.cms.name }}"
    owner: "{{ db.cms.user }}"
    encoding: UTF-8

- name: db - grant privileges
  postgresql_privs:
    db: "{{ db.cms.name }}"
    privs: ALL
    type: database
    role: "{{ db.cms.user }}"

- name: wp - user auth rule
  postgresql_pg_hba:
    dest: /etc/postgresql/{{ db.ver }}/main/pg_hba.conf
    contype: hostssl
    users: "{{ db.cms.user }}"
    databases: "{{ db.cms.name}}"
    source: "{{ vpn.gate }}/{{ vpn.prefix }}"
    method: scram-sha-256
  notify: handlers - reload postgresql service
