---

- name: filebeat - install filebeat 
  apt:
    name: filebeat
    state: latest

- name: filebeat - add cron job
  cron:
    name: start  aftert reboot server
    special_time: reboot
    job: "/bin/sleep 360 && /bin/systemctl start filebeat.service"

- name: filebeat - make cert dir
  file:
    name: /etc/filebeat/cert
    state: directory
    owner: root
    group: root
    mode: 0770
  when: when: ansible_hostname != server1.name

- name: filebeat - copy cert
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: root
    group: root
    mode: 0600
  with_items:
    - {src: '/share/easy_rsa/pki/ca.crt', dest: '/etc/filebeat/cert/ca.crt'}
    - {src: '/share/easy_rsa/pki/issued/client-{{ ansible_hostname }}.crt', dest: '/etc/filebeat/cert/log-{{ ansible_hostname }}.crt'}
    - {src: '/share/easy_rsa/pki/private/client-{{ ansible_hostname }}.key', dest: '/etc/filebeat/cert/log-{{ ansible_hostname }}.key'}
  notify: handlers - restart filebeat service
  when: when: ansible_hostname != server1.name

- name: filebeat - copy config
  template:
    src: /share/beats_conf/{{ ansible_hostname }}
    dest: /etc/filebeat/filebeat.yml 
    mode: 0644
    follow: yes
  notify: handlers - restart filebeat service
  register: config_changed

- name: filedeat - loads kibana dashboards
  command: filebeat setup
  when: ansible_hostname == server1.name|string and config_changed is changed

- name: filebeat - start and disable filebeat service
  systemd:
    daemon_reload: yes
    name: filebeat.service
    enabled: no
    state: started
