---

- name: Install kibana
  apt:
    name: kibana
    state: latest

- name: Configure kibana
  template:
    src: kibana.yml
    dest: /etc/kibana/kibana.yml
    mode: 0660

- name: Systemd reread
  systemd:
    daemon_reload: yes

- name: Restart and Disable kibana
  systemd:
    name: kibana.service
    enabled: no
    state: restarted

- name: Config cron
  include_tasks: kibana_cron.yml
