---

- name: Check list
  stat:
    path: /etc/apt/sources.list.d/elastic-7.x.list
  register: list

- name: Add repo
  template:
    src: elastic-7.x.list
    dest: /etc/apt/sources.list.d/elastic-7.x.list
    mode: 0644
  when: list.stat.isreg is not defined

- name: apt update
  apt:
    update_cache: yes

- name: Install java
  apt:
    pkg:
    - openjdk-11-jre-headless
    - uuid-runtime
    - pwgen
    
- name: Install Elasticsearch
  import_tasks: elastic.yml

- name: Install Kibana
  import_tasks: kibana.yml
