---

- name: grafana - config db
  include_tasks: db.yml
  when: ansible_hostname == server3.name|string

- name: grafana - install grafana
  include_tasks: install.yml
  when: ansible_hostname == server1.name|string
