---

- name: SkillFactory final project playbook
  hosts: server1.novpn
  gather_facts: yes
  become: true
  become_user: root
  vars_files:
  - secret.yml
  roles:
  - {role: test, tags: test}

#start novpn
#openvpn novpn
#bind9 novpn
#postgreslq db
#web web
#certbot web
#www web
#mail web
#pgadmin web
#elastic elk
#logs vpn
#zabbix vpn
#grafana grafana
