---

- name: test - novpn
  hosts: novpn
  gather_facts: yes
  become: true
  become_user: root
  become_method: sudo
  vars_files:
    - secret.yml
  roles:
    - test
  tags:
    - test

- name: test - vpn 
  hosts: vpn
  gather_facts: yes
  become: true
  become_user: root
  become_method: sudo
  vars_files:
    - secret.yml
  roles:
    - test
  tags:
    - vtest

- name: start
  hosts: novpn
  gather_facts: yes
  become: true
  become_user: root
  become_method: sudo
  vars_files:
    - secret.yml
  roles:
    - start
  tags:
    - start

- name: openvpn
  hosts: novpn
  gather_facts: yes
  become: true
  become_user: root
  become_method: sudo
  vars_files:
    - secret.yml
  roles:
    - openvpn
  tags:
    - openvpn

#bind9 novpn
#postgreslq db
#web web
#certbot web
#www web
#mail web
#pgadmin web
#elastic elk
#logs vpn
#zabbix vpn
#grafana grafana
