---

- hosts: server1.novpn
  tags: novpn
  gather_facts: yes
  become: true
  become_user: root
  become_method: sudo
  roles:
    - {role: test, tags: test}
    - {role: start, tags: start}
    - {role: openvpn, tags: openvpn}
  vars_files:
    - secret.yml

- hosts: server1.vpn
  tags: vpn
  gather_facts: yes
  become: true
  become_user: root
  become_method: sudo
  roles:
    - {role: test, tags: vtest}
  vars_files:
    - secret.yml

#bind9 novpn
#postgreslq db
#web web
#certbot web
#www web
#mail web
#pgadmin web
#elastic elk
#logs vpn
#zabbix vpn
#grafana grafana
