---

- hosts: novpn
  become: true
  become_user: root
  become_method: sudo
  gather_facts: yes
  vars_files:
    - secret.yml 
  tags:
    - novpn
    - test
    - start
    - openvpn

- hosts: novpn
  become: true
  become_user: root
  become_method: sudo
  vars_files:
    - secret.yml
  roles:
    - {role: test, tags: test}
    - {role: start, tags: start}
    - {role: openvpn, tags: openvpn}
  tags:
    - novpn

- hosts: vpn
  become: true
  become_user: root
  become_method: sudo
  gather_facts: yes
  vars_files:
    - secret.yml
  tags:
    - vpn
    - vtest 

- hosts: vpn
  become: true
  become_user: root
  become_method: sudo
  vars_files:
    - secret.yml
  roles:
    - {role: test, tags: vtest}
  tags:
    - vpn

# postgreslq db
#web web
#certbot web
#www web
#mail web
#pgadmin web
#elastic elk
#logs vpn
#zabbix vpn
#grafana grafana
