---

- hosts: novpn
  become: true
  become_user: root
  become_method: sudo
  vars_files:
    - secret.yml
  roles:
    - {role: facts,       tags: [test, start, openvpn, security]}
    - {role: test,        tags: test}
    - {role: start,       tags: start}
    - {role: openvpn,     tags: openvpn}
    - {role: security,    tags: security}
  tags:
    - novpn

- hosts: vpn 
  become: true
  become_user: root
  become_method: sudo
  vars_files:
    - secret.yml
  roles:
    - {role: facts,       tags: [vpntest, dns]}
    - {role: test,        tags: vpntest}
    - {role: dns,         tags: dns}
  tags:
    - vpn 

- hosts: web 
  become: true
  become_user: root
  become_method: sudo
  vars_files:
    - secret.yml
  roles:
    - {role: facts,       tags: [webtest, lnap, ssl, mail]}
    - {role: test,        tags: webtest}
    - {role: lnap,        tags: lnap}
    - {role: ssl,         tags: ssl}
    - {role: mail,        tags: mail}
  tags:
    - web

- hosts: [web, db]
  become: true
  become_user: root
  become_method: sudo
  vars_files:
    - secret.yml
  roles:
    - {role: facts,       tags: [wwwtest, wordpress, postgres]}
    - {role: test,        tags: wwwtest}
    - {role: postgres,    tags: postgres}
    - {role: wordpress,   tags: wordpress}
  tags:
    - www

#elastic elk
#logs vpn
#zabbix vpn
#grafana grafana
