---

#################################################################
## TESTING TASKS                                               ##
#################################################################
- hosts: [ server1.novpn ]
  become: true
  become_user: root
  become_method: sudo
  gather_facts: yes
  vars_files:
    - secret.yml
  tasks:
    - name: nginx - 
      lineinfile:
        path: /share/nginx.service
        insertbefore: '^After=(.*)$'
        line: 'Requires=apache2.service openvpn@{{ ansible_hostname }}.service'
    - name: nginx -
      replace:
        path: /share/nginx.service
        regexp: "^After=(.*)openvpn@{{ ansible_hostname }}.service(.*)$"
        replace: "zero"
      check_mode: yes
      register: line_vpn_exist
    - name: nginx -
      lineinfile:
        path: /share/nginx.service
        regexp: '^(After=.*)$'
        line: \g<1> openvpn@{{ ansible_hostname }}.service
        backrefs: yes
      when: line_vpn_exist is not changed
    - name: nginx -
      replace:
        path: /share/nginx.service
        regexp: "^After=(.*)apache2.service(.*)$"
        replace: "zero"
      check_mode: yes
      register: line_apache_exist
    - name: nginx -
      lineinfile:
        path: /share/nginx.service
        regexp: '^(After=.*)$'
        line: \g<1> apache2.service
        backrefs: yes
      when: line_apache_exist is not changed
    - name: nginx -
      lineinfile:
        path: /share/nginx.service
        insertafter: '^KillMode=(.*)$'
        line: 'Restart=on-failure'
    - name: nginx -
      lineinfile:
        path: /share/nginx.service
        insertafter: '^Restart=(.*)$'
        line: 'RestartSec=60'

#   - name: ping
#     ping:
#   - name: show facts
#     debug:
#       var: rc_info
#   - name: disables and resets firewall to installation defaults
#     ufw:
#       state: reset
  tags:
    - test

#################################################################
##    1    ansible-playbook /ansible/play.yml -t init          ##
##    2    ansible-playbook /ansible/play.yml -t openvpn       ##
#################################################################
- hosts: [ novpn ]
  become: true
  become_user: root
  become_method: sudo
  vars_files:
    - secret.yml
  roles:
    - {role: init,        tags: init}
    - {role: openvpn,     tags: openvpn}
  tags:
    - novpn

#################################################################
##    3    ansible-playbook /ansible/play.yml -t bind          ##
#################################################################
- hosts: [ vpn ]
  become: true
  become_user: root
  become_method: sudo
  gather_facts: yes
  vars_files:
    - secret.yml
  roles:
    - bind
  tags:
    - bind 

#################################################################
##    4    ansible-playbook /ansible/play.yml -t web           ##
#################################################################
- hosts: [ web ]
  become: true
  become_user: root
  become_method: sudo
  gather_facts: yes
  vars_files:
    - secret.yml
  roles:
    - web
  tags:
    - web

#################################################################
## 6    ansible-playbook /ansible/play.yml -t postgres         ##
## 7    ansible-playbook /ansible/play.yml -t wordpress        ##
## 8    ansible-playbook /ansible/play.yml -t mail             ##
#################################################################
- hosts: [ web, db ]
  become: true
  become_user: root
  become_method: sudo
  vars_files:
    - secret.yml
  roles:
    - {role: postgres,    tags: postgres}
    - {role: wordpress,   tags: wordpress}
    - {role: mail,        tags: mail}
  tags:
    - www

#################################################################
## 9    ansible-playbook /ansible/play.yml -t zabbix           ##
#################################################################
- hosts: [ vpn ]
  become: true
  become_user: root
  become_method: sudo
  gather_facts: yes
  vars_files:
    - secret.yml
  roles:
    - zabbix
  tags:
    - zabbix

#################################################################
## 10   ansible-playbook /ansible/play.yml -t grafana          ##
#################################################################
- hosts: [ main, db ]
  become: true
  become_user: root
  become_method: sudo
  gather_facts: yes
  vars_files:
    - secret.yml
  roles:
    - grafana
  tags:
    - grafana

#################################################################
## 11   ansible-playbook /ansible/play.yml -t elk              ##
#################################################################
- hosts: [ db ]
  become: true
  become_user: root
  become_method: sudo
  gather_facts: yes
  vars_files:
    - secret.yml
  roles:
    - elk
  tags:
    - elk

#################################################################
## 12   ansible-playbook /ansible/play.yml -t beats            ##
#################################################################
- hosts: [ main, web ]
  become: true
  become_user: root
  become_method: sudo
  gather_facts: yes
  vars_files:
    - secret.yml
  roles:
    - beats
  tags:
    - beats
