---

- hosts: novpn
  become: true
  become_user: root
  become_method: sudo
  vars_files:
    - secret.yml
  roles:
    - {role: facts,       tags: [test, init_all, openvpn, security]}
    - {role: test,        tags: test}
    - {role: init_all,    tags: init_all}
    - {role: openvpn,     tags: openvpn}
    - {role: security,    tags: security}
  tags:
    - novpn

- hosts: vpn 
  become: true
  become_user: root
  become_method: sudo
  vars_files:
    - secret.yml
  roles:
    - {role: facts,       tags: [test_vpn, dns, zabbix, logs]}
    - {role: test,        tags: test_vpn}
    - {role: dns,         tags: dns}
    - {role: zabbix,      tags: zabbix}
    - {role: logs,        tags: logs}
  tags:
    - vpn 

- hosts: main
  become: true
  become_user: root
  become_method: sudo
  vars_files:
    - secret.yml
  roles:
    - {role: facts,       tags: [test_main, rsa]}
    - {role: test,        tags: test_main}
    - {role: rsa,         tags: rsa}
  tags:
    - main

- hosts: publick 
  become: true
  become_user: root
  become_method: sudo
  vars_files:
    - secret.yml
  roles:
    - {role: facts,       tags: [test_publick, lnap, ssl]}
    - {role: test,        tags: test_publick}
    - {role: lnap,        tags: lnap}
    - {role: ssl,         tags: ssl}
  tags:
    - publick

- hosts: db_elk
  become: true
  become_user: root
  become_method: sudo
  vars_files:
    - secret.yml
  roles:
    - {role: facts,       tags: [test_db, elk]}
    - {role: test,        tags: test_db}
    - {role: elk,         tags: elk}
  tags:
    - db_elk

- hosts: [publick, db_elk]
  become: true
  become_user: root
  become_method: sudo
  vars_files:
    - secret.yml
  roles:
    - {role: facts,       tags: [test_www, wordpress, postgres, mail]}
    - {role: test,        tags: test_www}
    - {role: postgres,    tags: postgres}
    - {role: wordpress,   tags: wordpress}
    - {role: mail,        tags: mail}
  tags:
    - www

- hosts: [main, db_elk]
  become: true
  become_user: root
  become_method: sudo
  vars_files:
    - secret.yml
  roles:
    - {role: facts,       tags: [test_o, grafana]}
    - {role: test,        tags: test_o}
    - {role: grafana,     tags: grafana}
  tags:
    - o
