---

#############
## TESTING ##
#############
- hosts: [ server1.novpn ]
  become: true
  become_user: root
  become_method: sudo
  gather_facts: yes
  vars_files:
    - secret.yml
  roles:
    - test
  tags:
    - test

###############
## RESET UFW ##
###############
- hosts: [ novpn ]
  become: true
  become_user: root
  become_method: sudo
  gather_facts: no
  vars_files:
    - secret.yml
  tasks:
    - name: disables and resets firewall to installation defaults
      ufw:
        state: reset
  tags:
    - reset_ufw

################################################
## 1. init - FIRST INITIALIZATION             ##
## 2. openvpn - SETUP VIRTUAL PRIVATE NETWORK ##
################################################
- hosts: [ novpn ]
  become: true
  become_user: root
  become_method: sudo
  vars_files:
    - secret.yml
  roles:
    - {role: facts,       tags: [ init, openvpn ]}
    - {role: init,        tags: init}
    - {role: openvpn,     tags: openvpn}
  tags:
    - novpn

################################
## 3. bind - SETUP DNS SERVER ##
################################
- hosts: [ vpn ]
  become: true
  become_user: root
  become_metihod: sudo
  gather_facts: yes
  vars_files:
    - secret.yml
  roles:
    - bind
  tags:
    - bind 

- hosts: [ web ]
  become: true
  become_user: root
  become_method: sudo
  vars_files:
    - secret.yml
  roles:
    - {role: facts,       tags: [ lnap, ssl ]}
    - {role: lnap,        tags: lnap}
    - {role: ssl,         tags: ssl}
  tags:
    - web

- hosts: [ web, db ]
  become: true
  become_user: root
  become_method: sudo
  vars_files:
    - secret.yml
  roles:
    - {role: facts,       tags: [ wordpress, postgres, mail ]}
    - {role: postgres,    tags: postgres}
    - {role: wordpress,   tags: wordpress}
    - {role: mail,        tags: mail}
  tags:
    - www

- hosts: [ vpn ]
  become: true
  become_user: root
  become_method: sudo
  gather_facts: yes
  vars_files:
    - secret.yml
  roles:
    - zabbix
  tags:
    - zabbix

- hosts: [ main, db ]
  become: true
  become_user: root
  become_method: sudo
  gather_facts: yes
  vars_files:
    - secret.yml
  roles:
    - grafana
  tags:
    - grafana

- hosts: [ db ]
  become: true
  become_user: root
  become_method: sudo
  gather_facts: yes
  vars_files:
    - secret.yml
  roles:
    - elk
  tags:
    - elk

- hosts: [ main, web ]
  become: true
  become_user: root
  become_method: sudo
  gather_facts: yes
  vars_files:
    - secret.yml
  roles:
    - beats
  tags:
    - beats
