---

- name: sshd - configure {{ server2.name }}
  replace:
    path: /etc/ssh/sshd_config
    regexp: '^#ListenAddress 0.0.0.0$'
    replace: 'ListenAddress 0.0.0.0'
  when: ansible_hostname == server2.name|string

- name: sshd - configure other servers
  replace:
    path: /etc/ssh/sshd_config
    regexp: '^#ListenAddress 0.0.0.0$'
    replace: 'ListenAddress {{ ansible_facts.default_ipv4.address }}'
  when: ansible_hostname != server2.name|string

- name: sshd - configure other servers to vpn
  lineinfile:
    path: /etc/ssh/sshd_config
    line: 'ListenAddress {{ ansible_facts.tun0.ipv4.address }}'
    insertafter: 'ListenAddress {{ ansible_facts.default_ipv4.address }}'
    state: present
  when: ansible_hostname != server2.name|string

- name: sshd - reload
  systemd:
    name: sshd.service
    enabled: yes
    state: reloaded

- name: cron - reload sshd after reboot server
  cron:
    name: reload sshd  after reboot server
    special_time: reboot
    job: "/bin/sleep 30 && /bin/systemctl reload sshd.service"
