---

- name: ufw - allow outgoing trafic
  ufw:
    default: allow
    direction: outgoing

- name: ufw - deny incoming trafic
  ufw:
    default: deny
    direction: incoming

- name: ufw - allow ssh on {{ server2.name }} 
  ufw:
    rule: allow
    name: OpenSSH
  when: ansible_hostname == server2.name|string

- name: ufw - allow ssh on other servers
  ufw:
    rule: allow
    proto: tcp
    interface: "{{ ansible_facts.default_ipv4.interface }}"
    direction: in
    to_port: 22
  when: ansible_hostname != server2.name|string

- name: vpnserver - add openvpn ufw rule
  ufw:
    rule: allow
    proto: udp
    port: 1194
    direction: in
    interface: eth0
  when: ansible_hostname == server1.name|string

- name: vpnserver - add ssh ufw rule
  ufw:
    rule: allow
    proto: tcp
    port: 22
    direction: in
    interface: tun0
  when: ansible_hostname != server2.name|string

- name: ufw - enable
  ufw:
    state: enabled
  register: ufw_enabled

- name: ufw - reload
  ufw:
    state: reloaded
  when: ufw_enabled is not changed
