---

- name: apache - copy config
  template:
    src: wordpress.conf
    dest: /etc/apache2/sites-available/wordpress.conf
    mode: 0644
    owner: root
    group: root

- name: apache - enable wordpress config
  lineinfile:
    path: /etc/apache2/sites-available/apache.conf
    insertafter: '^  # Service list'
    line: '  Include  /etc/apache2/sites-available/wordpress.conf'

- name: apache - reload
  systemd:
    name: apache2.service
    state: reloaded
