---

- name: clear - backup www
  copy:
    src: /var/www/
    dest: /var/www_backup
    remote_src: yes
    force: no

- name: clear - remove www
  file:
    path: /var/www/
    state: absent

- name: clear - make new www dir
  file:
    path: /var/www/
    state: directory
    mode: 0755
    owner: root
    group: root
