---

- name: wordpress - backup and clear www
  include_tasks: clear.yml
  when: ansible_hostname == server2.name|string

- name: wordpress - install
  include_tasks: wp.yml
  when: ansible_hostname == server2.name|string

- name: wordpress - config db
  include_tasks: db.yml
  vars:
    ansible_become_user: postgres
  when: ansible_hostname == server3.name|string

- name: wordpress - config apache
  include_tasks: apache.yml
  when: ansible_hostname == server2.name|string
