---

- name: Install_DNS_server
  apt:
    name: "bind9"
    state: "latest"

- name: Start_DNS_server
  ansible.builtin.systemd:
    name: "named.service"
    enabled: "yes"
    state: "started"

- name: Make_dir_for_my_zones
  ansible.builtin.file:
    path: "{{ item.path }}"
    state: "directory"
    mode: "0755"
  with_items:
  - {path: '/etc/bind/myzones'}
  - {path: '/etc/bind/myzones/{{ domain.second }}'}
  - {path: '/etc/bind/myzones/local'}

- name: Config_server
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: 0644
  with_items:
  - {src: 'local.db',dest: '/etc/bind/myzones/local/local.db'}
  - {src: 'public.db',dest: '/etc/bind/myzones/{{ domain.second }}/{{ domain.second }}.db'}
  - {src: 'named.conf.local',dest: '/etc/bind/named.conf.local'}
  - {src: 'named.conf.options',dest: '/etc/bind/named.conf.options'}
  notify:
    handler_reconfig_server
