---

- name: ufw - disables and resets firewall to installation defaults
  ufw:
    state: reset

- name: ufw - allow outgoing trafic
  ufw:
    default: allow
    direction: outgoing

- name: ufw - deny incoming trafic
  ufw:
    default: deny
    direction: incoming

- name: ufw -  reject IPv6
  ufw:
    rule: reject
    proto: ipv6

- name: ufw - allow ssh on {{ server2.name }} 
  ufw:
    rule: allow
    name: OpenSSH
  when: ansible_hostname == server2.name|string

- name: ufw - allow ssh on other servers (novpn)
  ufw:
    rule: allow
    proto: tcp
    interface: "{{ ansible_facts.default_ipv4.interface }}"
    direction: in
    to_port: 22
    src: "{{ item }}"
  loop:
    - "{{ server1.novpn_ip }}"
    - "{{ server2.novpn_ip }}"
  when: ansible_hostname != server2.name|string

- name: ufw - allow ssh on other servers (vpn)
  ufw:
    rule: allow
    proto: tcp
    port: 22
    direction: in
    interface: "{{ ansible_facts.tun0.device }}"
    from_ip: "{{ vpn.gate }}/{{ vpn.prefix }}"
  when: ansible_hostname != server2.name|string

- name: ufw - add openvpn ufw rule
  ufw:
    rule: allow
    proto: udp
    port: 1194
    direction: in
    interface: "{{ ansible_facts.default_ipv4.interface }}"
  when: ansible_hostname == server1.name|string

- name: ufw - enable
  ufw:
    state: enabled
  register: ufw_enabled

- name: ufw - reload
  ufw:
    state: reloaded
  when: ufw_enabled is not changed
