---

- name: kibana - install kibana
  apt:
    name: kibana
    state: latest

- name: kibana - add ufw rule
  ufw:
    rule: allow
    port: 5601
    direction: in
    interface: "{{ ansible_facts.tun0.device }}"
    from_ip: '{{ vpn.gate }}/{{ vpn.prefix }}'
  notify: handlers - reload ufw

- name: kibana - copy config
  template:
    src: kibana.yml
    dest: /etc/kibana/kibana.yml
    owner: root
    group: kibana
    mode: 0640
  notify: handlers - restart kibana service

- name: kibana - start and enable kibana service
  systemd:
    daemon_reload: yes
    name: kibana.service
    enabled: yes
    state: started
