---

- name: rmdir
  file:
    path: "/var/www"
    state: "absent"

- name: mkdir
  file:
    path: "/var/www"
    state: "directory"
    mode: "0755"

- name: Download_git_www
  ansible.builtin.git:
    repo: "git@github.com:mkAdmin11/www.git"
    dest: "/var/www"

- name: Change_www
  shell: "{{ item.shell }}"
  with_items:
  - {shell: 'find /var/www/wordpress -type d -exec chmod 755 {} \;'}
  - {shell: 'find /var/www/wordpress -type f -exec chmod 644 {} \;'}
  - {shell: 'chown -R www-data:www-data /var/www/wordpress'}

- name: config_apache
  template:
    src: "apache.conf"
    dest: "/etc/apache2/sites-enabled/apache.conf"
    mode: "0644"
  notify:
    handler_restart_apache
