---

- name: elastic - install elasticsearch
  apt:
    name: elasticsearch
    state: latest

- name: elastic - start and disable elasticsearch service
  systemd:
    daemon_reload: yes
    name: elasticsearch.service
    enabled: no
    state: started

- name: elastic - add cron job
  cron:
    name: start elasticsearch after reboot server
    special_time: reboot
    job: "/bin/sleep 40 && /bin/systemctl start elasticsearch.service"

- name: elastic - add ufw rule
  ufw:
    rule: allow
    port: "{{ item }}"
    direction: in
    interface: "{{ ansible_facts.tun0.device }}"
    from_ip: '{{ vpn.gate }}/{{ vpn.prefix }}'
  with_items:
    - 9300
    - 9200
  register: ufw_changed
  
- name: elastic - reload ufw
  ufw:
    state: reloaded
  when: ufw_changed is changed

- name: elastic - copy config
  template:
    src: elasticsearch.yml
    dest: /etc/elasticsearch/elasticsearch.yml
    mode: 0660
  register: conf_changed

- name: elastic - restart elasticsearch service
  systemd:
    name: elasticsearch.service
    state: restarted
  when: conf_changed is changed
