---

- name: kibana - install kibana
  apt:
    name: kibana
    state: latest

- name: kibana - add ufw rule
  ufw:
    rule: allow
    port: 5601
    direction: in
    interface: "{{ ansible_facts.tun0.device }}"
    from_ip: '{{ vpn.gate }}/{{ vpn.prefix }}'
  notify: handlers - reload ufw

- name: kibana - add cron job
  cron:
    name: start kibana after reboot server
    special_time: reboot
    job: "/bin/sleep 180 && /bin/systemctl start kibana.service"

- name: kibana - copy config
  template:
    src: kibana.yml
    dest: /etc/kibana/kibana.yml
    mode: 0660
  notify: handlers - restart kibana service

- name: kibana - start and disable kibana service
  systemd:
    daemon_reload: yes
    name: kibana.service
    enabled: no
    state: started
