---

- name: rmdir
  file:
    path: "{{ item.path }}"
    state: "absent"
  with_items:
  - {path: '/etc/nginx/sites-enabled/forcustomer.conf'}
  - {path: '/etc/nginx/sites-enabled/{{ domain.second }}.conf'}
