---

- name: task_certbot
  apt:
    pkg:
    - certbot
    - python3-certbot-nginx
    - apt-transport-https
    - python
    - python-dev
    - gcc
    - dialog
    - libaugeas0
    - augeas-lenses
    - libssl-dev
    - libffi-dev
    - ca-certificates

- name: Get_second_stats
  stat:
    path: /etc/letsencrypt/live/{{ domain.second }}{{ domain.first }}
  register: second

- name: Get_third_stat
  stat:
    path: /etc/letsencrypt/live/forcustomer.{{ domain.second }}{{ domain.first }}
  register: third

- name: Get_DH_stat
  stat:
    path: /etc/letsencrypt/ssl-dhparams.pem
  register: dh

- name: Generate_cert
  shell: letsencrypt certonly --webroot --agree-tos -w /var/www/forcustomer -m admin@{{ domain.second }}{{ domain.first }} -d {{ domain.second }}{{ domain.first }}
  when: second.stat.isdir is not defined

- name: Generate_cert_forcustomer
  shell: letsencrypt certonly --webroot --agree-tos -w /var/www/forcustomer -m admin@{{ domain.second }}{{ domain.first }} -d forcustomer.{{ domain.second }}{{ domain.first }}
  when: third.stat.isdir is not defined

- name: Generate_dh
  shell: openssl dhparam -out /etc/letsencrypt/ssl-dhparams.pem 2048
  when: dh.stat.isreg is not defined

- name: Tasks_clear_config
  import_tasks: clear.yml

- name: task_config_nginx
  template:
    src: "nginx.conf"
    dest: "/etc/nginx/sites-enabled/nginx.conf"
    mode: 0644
  notify:
    handler_restart_nginx
