---

- name: handlers - update apt cache
  apt:
    update_cache: yes

- name: handlers - reload apache service
  systemd:
    name: apache2.service
    state: reloaded

- name: handlers - reload postgresql service
  become_user: root
  systemd:
    name: postgresql.service
    state: reloaded

- name: handlers - restart postgresql service
  become_user: root
  systemd:
    name: postgresql.service
    state: restarted

- name: handlers - reload ufw
  ufw:
    state: reloaded
