---

- name: db - unzip roundcube.tar.gz
  unarchive:
    src: /share/roundcube.tar.gz
    dest: /tmp
    list_files: yes
  register: unzip

- name: db - create user
  postgresql_user:
    name: "{{ db.roundcube.user }}"
    password: "{{ db.roundcube.pass }}"
    role_attr_flags: SUPERUSER

- name: db - create db
  postgresql_db:
    name: "{{ db.roundcube.name }}"
    owner: "{{ db.roundcube.user }}"
    encoding: UTF-8

- name: db - grant privileges
  postgresql_privs:
    db: "{{ db.roundcube.name }}"
    privs: ALL
    type: database
    role: "{{ db.roundcube.user }}"

- name: roundcube - check db
  postgresql_info:
    filter:
      - databases
  register: rc_info

- name: db - restore db
  postgresql_db:
    name: "{{ db.roundcube.name }}"
    state: restore
    target: /tmp/{{ unzip.files[0] }}/SQL/postgres.initial.sql
    target_opts: pg_restore
  when: rc_info.databases.db_rc.size == rc_info.databases.template1.size 

- name: db - user auth conf
  postgresql_pg_hba:
    dest: /etc/postgresql/{{ db.ver }}/main/pg_hba.conf
    contype: hostssl
    users: "{{ db.roundcube.user }}"
    databases: "{{ db.roundcube.name }}"
    source: "{{ vpn.gate }}/{{ vpn.prefix }}"
    method: scram-sha-256
  notify:
    - handlers - reload postgresql service
