---

- name: dovecot - install
  apt:
    pkg:
    - dovecot-core
    - dovecot-imapd
    - dovecot-pop3d
    - dovecot-lmtpd

- name: dovecot - stop and disable
  systemd:
    name: dovecot.service
    enabled: no
    state: stopped

- name: dovecot - cron
  cron:
    name: start cron after reboot server
    special_time: reboot
    job: "/bin/sleep 30 && /bin/systemctl start apache2.service"

- name: dovecot - add mail group
  group:
    name: vmail
    state: present
    gid: 5000

- name: dovecot - add mail user
  user:
    name: vmail
    comment: "virtual mail user"
    uid: 5000
    group: vmail
    home: "/var/mail/vhosts"
    create_home: yes

- name: dovecot - make mail dir
  file:
    path: "/var/mail/vhosts/{{ domain.second }}{{ domain.top }}"
    state: directory
    owner: vmail 
    group: vmail
    mode: 0770

- name: dovecot - listen adress
  lineinfile:
    path: /etc/dovecot/dovecot.conf
    regexp: '^#listen = '
    line: 'listen = {{ ansible_facts.tun0.ipv4.address }}'

- name: dovecot - imap only
  lineinfile:
    path: /etc/dovecot/dovecot.conf
    regexp: '!include_try /usr/share/dovecot/protocols.d/'
    line: '!include_try /usr/share/dovecot/protocols.d/imapd.protocol'

- name: dovecot - copy config
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: 0644
  with_items:
  - {src: '10-auth.conf',dest: '/etc/dovecot/conf.d/10-auth.conf'}
  - {src: '10-master.conf',dest: '/etc/dovecot/conf.d/10-master.conf'}
  - {src: 'auth-passwdfile.conf.ext',dest: '/etc/dovecot/conf.d/auth-passwdfile.conf.ext'}
  - {src: '10-mail.conf',dest: '/etc/dovecot/conf.d/10-mail.conf'}
  - {src: '10-ssl.conf',dest: '/etc/dovecot/conf.d/10-ssl.conf'}
  - {src: 'dovecot-users',dest: '/etc/dovecot/dovecot-users'}

- name: dovecot - add ufw rule
  ufw:
    rule: allow
    proto: tcp
    interface: "{{ ansible_facts.tun0.device }}"
    direction: in
    to_port: "{{ item }}"
  loop:
    - 143
    - 993

- name: dovecot - reload ufw
  ufw:
    state: reloaded

- name: dovecot - start service
  systemd:
    name: dovecot.service
    state: started
