---

- name: dovecot - install
  apt:
    pkg:
    - dovecot-core
    - dovecot-imapd
    - dovecot-pop3d
    - dovecot-lmtpd

- name: dovecot - stop and disable
  systemd:
    name: dovecot.service
    enabled: yes
    state: stopped

- name: dovecot - add mail group
  group:
    name: vmail
    state: present
    gid: 5000

- name: dovecot - add mail user
  user:
    name: vmail
    comment: "virtual mail user"
    uid: 5000
    group: vmail
    home: "/var/mail/vhosts"
    create_home: yes

- name: dovecot - make mail dir
  file:
    path: "/var/mail/vhosts/{{ domain.second }}{{ domain.top }}"
    state: directory
    owner: vmail 
    group: vmail
    mode: 0770

- name: dovecot - copy config
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: 0644
  with_items:
  - {src: '10-master.conf',dest: '/etc/dovecot/conf.d/10-master.conf'}
  - {src: 'auth-passwdfile.conf.ext',dest: '/etc/dovecot/conf.d/auth-passwdfile.conf.ext'}
  - {src: 'dovecot-users',dest: '/etc/dovecot/dovecot-users'}
  - {src: 'dovecot.conf',dest: 'dovecot.conf'}

- name: dovecot - authentication processes
  replace:
    path: /etc/dovecot/conf.d/10-auth.conf
    regexp: "{{ item.regexp }}"
    replace: "{{ item.replace }}"
  with_items:
    - {regexp: '^!include auth-system.conf.ext', replace: '#!include auth-system.conf.ext'}
    - {regexp: '^#!include auth-passwdfile.conf.ext', replace: '!include auth-passwdfile.conf.ext'}

- name: dovecot - mail location
  replace:
    path: /etc/dovecot/conf.d/10-mail.conf
    regexp: '^mail_location = mbox:~/mail:INBOX=/var/mail/%u'
    replace: 'mail_location = maildir:/var/mail/vhosts/%d/%n'

- name: dovecot - ssl
  replace:
    path: /etc/dovecot/conf.d/10-ssl.conf
    regexp: '^ssl = yes'
    replace: 'ssl = no'

- name: dovecot - start service
  systemd:
    name: dovecot.service
    state: started
