---

- name: Config Postfix
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: 0644
  with_items:
  - {src: 'main.cf',dest: '/etc/postfix/main.cf'}
  - {src: 'virtual_mailbox_domains',dest: '/etc/postfix/virtual_mailbox_domains'}
  - {src: 'master.cf',dest: '/etc/postfix/master.cf'}

- name: Postfix lookup
  shell: "postmap /etc/postfix/virtual_mailbox_domains"
  notify:
    handler_restart_postfix

- name: Install Dovecot
  apt:
    pkg:
    - dovecot-core
    - dovecot-imapd
    - dovecot-pop3d
    - dovecot-lmtpd

- name: Add group
  group:
    name: vmail
    state: present
    gid: 5000

- name: Add user
  user:
    name: vmail
    comment: "virtual mail user"
    uid: 5000
    group: vmail
    home: "/var/mail/vhosts"
    create_home: yes

- name: Get dir stats
  stat:
    path: "/var/mail/vhosts/{{ domain.second }}{{ domain.first }}"
  register: maildir
 
- name: Make dir
  file:
    path: "/var/mail/vhosts/{{ domain.second }}{{ domain.first }}"
    state: directory
    owner: vmail 
    group: vmail
    mode: 0770
  when: maildir.stat.isdir is not defined

- name: Dovecot listen
  shell: "sed -i.bak 's/#listen = *, ::/listen = 0.0.0.0/g' /etc/dovecot/dovecot.conf"

- name: Config Dovecot
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: 0644
  with_items:
  - {src: '10-auth.conf',dest: '/etc/dovecot/conf.d/10-auth.conf'}
  - {src: '10-master.conf',dest: '/etc/dovecot/conf.d/10-master.conf'}
  - {src: 'auth-passwdfile.conf.ext',dest: '/etc/dovecot/conf.d/auth-passwdfile.conf.ext'}
  - {src: '10-mail.conf',dest: '/etc/dovecot/conf.d/10-mail.conf'}
  - {src: '10-ssl.conf',dest: '/etc/dovecot/conf.d/10-ssl.conf'}
  - {src: 'dovecot-users',dest: '/etc/dovecot/dovecot-users'}
  notify:
    handler_restart_dovecot
