---

- name: mail - install postfix
  include_tasks: postfix.yml
  when: ansible_hostname == server2.name|string

- name: mail - install dovecot
  include_tasks: dovecot.yml
  when: ansible_hostname == server2.name|string

- name: mail - install roundcube
  include_tasks: roundcube.yml
  when: ansible_hostname == server2.name|string

- name: mail - config apache
  include_tasks: apache.yml
  when: ansible_hostname == server2.name|string

- name: mail - config db
  include_tasks: db.yml
  vars:
    ansible_become_user: postgres
  when: ansible_hostname == server3.name|string

- name: mail - reload postgres service
  systemd:
    name: postgresql.service
    state: reloaded
  when: ansible_hostname == server3.name|string
