---

- name: roundcube - unzip roundcube.tar.gz
  unarchive:
    src: /share/roundcube.tar.gz
    dest: /tmp/
    owner: root
    group: root
    list_files: yes
  register: unzip

- name: roundcube - move source dir
  copy:
    src: /tmp/{{ unzip.files[0] }}
    dest: /var/www/mail/
    owner: www-data
    group: www-data
    remote_src: true

- name: roundcube - gen key
  set_fact:
    roundcude_key_gen: "{{ lookup('password', '/dev/null length=24 seed=inventory_hostname chars=ascii_letters,digits') }}"

- name: roundcube - copy config
  template:
    src: config.inc.php
    dest: /var/www/mail/config/config.inc.php
    mode: 0640
    owner: www-data
    group: www-data
