---

- name: Get script stat
  stat:
    path: /root/start.sh
  register: script

- name: Make script template
  block:
    - name: Make script
      file:
        path: /root/start.sh
        state: touch
        owner: root
        group: root
        mode: 0770
    - name: First line
      shell: echo "#!/bin/bash" > /root/start.sh
  when: skript.stat.isreg is not defined

- name: Job after reboot elk+db server
  cron:
    name: "Job after reboot"
    special_time: reboot
    job: "sleep 120 && /root/start.sh >/dev/null 2>&1"
  when: ansible_hostname == 'mk-server3'

- name: Job after reboot other servers
  cron:
    name: "Job after reboot"
    special_time: reboot
    job: "sleep 300 && /root/start.sh >/dev/null 2>&1"
  when: ansible_hostname != 'mk-server3'

- name: Sync cron
  cron:
    name: "{{ item.name }}"
    minute: "0"
    hour: "*/2"
    job: "{{ item.job }}"
  with_items:
  - {name: 'Sync mk-server2',job: 'rsync -arze ssh /share/ mk-adm2@mk-server2.local:/share/'}
  - {name: 'Reverce sync mk-server2',job: 'rsync -arze ssh mk-adm2@mk-server2.local:/share/ /share/'}
  - {name: 'Sync mk-server3',job: 'rsync -arze ssh /share/ mk-adm3@mk-server3.local:/share/'}
  - {name: 'Reverce sync mk-server3',job: 'rsync -arze ssh mk-adm3@mk-server3.local:/share/ /share/'}
  when: ansible_hostname == 'mk-server1'
