---

- name: ssl - install
  apt:
    pkg:
    - certbot
    - python3-certbot-nginx
    - python
    - python-dev
    - gcc
    - dialog
    - libaugeas0
    - augeas-lenses
    - libssl-dev
    - libffi-dev
    - ca-certificates

- name: ssl - generate cert
  command:
    creates: /etc/letsencrypt/live/{{ domain.second }}{{ domain.top }}/privkey.pem
    cmd: letsencrypt certonly --webroot --agree-tos -w /var/www/html -m admin@{{ domain.second }}{{ domain.top }} -d {{ domain.second }}{{ domain.top }}
  notify:
    - handlers - reload nginx service

- name: ssl - generate dh
  command:
    creates: /etc/letsencrypt/ssl-dhparams.pem
    cmd: openssl dhparam -out /etc/letsencrypt/ssl-dhparams.pem 2048
  notify:
    - handlers - reload nginx service

- name: ssl - config nginx
  template:
    src: nginx.conf
    dest: /etc/nginx/sites-available/nginx.conf
    mode: 0644
  notify:
    - handlers - reload nginx service
