---

- name: Remove dir
  file:
    path: "{{ item.path }}"
    state: absent
  with_items:
  - {path: '/etc/apache2/sites-enabled'}
  - {path: '/etc/nginx/sites-enabled'}

- name: Make dir
  file:
    path: "{{ item.path }}"
    state: directory
    mode: 0755
  with_items:
  - {path: '/etc/apache2/sites-enabled'}
  - {path: '/etc/nginx/sites-enabled'}
