---

- name: tasks_PHP
  import_tasks: "php.yml"

- name: Install_nginx
  apt:
    name: "nginx"
    state: "latest"

- name: Stop_nginx
  systemd:
    name: "nginx.service"
    enabled: "yes"
    state: "stopped"

- name: Install_apache2
  apt:
    name: "apache2"
    state: "latest"

- name: Stop_apache2
  systemd:
    name: "apache2.service"
    enabled: "yes"
    state: "stopped"

- name: tasks_apache2_lib
  import_tasks: "libapache.yml"

- name: tasks_clear_config
  import_tasks: "clear.yml"

- name: Config_nginx
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: "0644"
  with_items:
  - {src: 'nginx.conf', dest: '/etc/nginx/sites-enabled/nginx.conf'}
  - {src: 'forcustomer.conf', dest: '/etc/nginx/sites-enabled/forcustomer.conf'}
  notify:
    handler_start_nginx

- name: Config_apache2_port
  shell: sed -i.bak 's/Listen 80/Listen {{ ansible_facts.tun0.ipv4.address }}:8080/g' /etc/apache2/ports.conf

- name: Config_apache2
  template:
    src: "apache.conf"
    dest: "/etc/apache2/sites-enabled/apache.conf"
    mode: 0644
  notify:
    handler_start_apache2
