---

- name: Install PHP
  import_tasks: php.yml

- name: Install nginx
  apt:
    name: nginx
    state: latest

- name: Stop nginx
  systemd:
    name: nginx.service
    enabled: yes
    state: stopped

- name: Install Apache2
  apt:
    name: apache2
    state: latest

- name: Stop Apache2
  systemd:
    name: apache2.service
    enabled: no
    state: stopped

- name: Cron
  include_tasks: apache2_cron.yml

- name: Install Apache2 lib
  import_tasks: libapache.yml

- name: Clear config
  import_tasks: clear.yml

- name: Config nginx
  template:
    src: nginx.conf
    dest: /etc/nginx/sites-enabled/nginx.conf 
    mode: 0644
  notify:
    handler_start_nginx

- name: Set Apache2 port
  shell: "sed -i.bak 's/Listen 80/Listen {{ ansible_facts.tun0.ipv4.address }}:8080/g' /etc/apache2/ports.conf"

- name: Config Apache2
  template:
    src: apache.conf
    dest: /etc/apache2/sites-enabled/apache.conf
    mode: 0644
  notify:
    handler_start_apache2
