---

- name: postgres - collect facts
  gather_facts:

- name: postgres - set up postgres server
  include_tasks: dbms.yml
  when: ansible_hostname == server3.name|string

- name: postgres - add demo db
  include_tasks: demo.yml
  vars:
    ansible_become_user: postgres
  when: ansible_hostname == server3.name|string

- name: postgres - install pgadmin
  include_tasks: pgadmin.yml
  when: ansible_hostname == server2.name|string

- name: postgres - config apache
  include_tasks: apache.yml
  when: ansible_hostname == server2.name|string
