---

- name: Install elasticsearch
  apt:
    name: elasticsearch
    state: latest

- name: Increase startup timeout
  include_tasks: systemd.yml

- name: Systemd reread
  systemd:
    daemon_reload: yes

- name: Start and Disable elasticsearch
  systemd:
    name: elasticsearch.service
    enabled: no
    state: started

- name: Configure elasticsearch
  template:
    src: elasticsearch.yml
    dest: /etc/elasticsearch/elasticsearch.yml
    mode: 0660

- name: Restart elasticsearch
  systemd:
    name: elasticsearch.service
    state: restarted

- name: Config cron
  include_tasks: elastic_cron.yml

- name: Add ELK users
  shell: "{{ item.shell }}"
  with_items:
  - {shell: '/usr/share/elasticsearch/bin/elasticsearch-users useradd {{ elk.users.elastic.name }} -p {{ elk.users.elastic.pass }} -r {{ elk.users.elastic.role }}'}
  - {shell: '/usr/share/elasticsearch/bin/elasticsearch-users useradd {{ elk.users.kibana.name }} -p {{ elk.users.kibana.pass }} -r {{ elk.users.kibana.role }}'}
  - {shell: '/usr/share/elasticsearch/bin/elasticsearch-users useradd {{ elk.users.monitoring.name }} -p {{ elk.users.monitoring.pass }} -r {{ elk.users.monitoring.role }}'}
  ignore_errors: True
