---

- name: Check dir
  stat:
    path: /etc/systemd/system/elasticsearch.service.d
  register: dir

- name: Make dir
  file:
    path: /etc/systemd/system/elasticsearch.service.d
    state: directory
    mode: 0755
  when: dir.stat.isdir is not defined

- name: Upload Config
  template:
    src: startup-timeout.conf
    dest: /etc/systemd/system/elasticsearch.service.d/startup-timeout.conf
    mode: 0644
