---

- name: wordpress - collect facts
  gather_facts:

- name: wordpress - prepare share
  include_tasks: share.yml
  when: ansible_hostname == server1.name|string

- name: wordpress - backup and clear www
  include_tasks: clear.yml
  when: ansible_hostname == server2.name|string

- name: wordpress - install
  include_tasks: wp.yml
  when: ansible_hostname == server2.name|string

- name: wordpress - config db
  include_tasks: db.yml
  vars:
    ansible_become_user: postgres
  when: ansible_hostname == server3.name|string

- name: wordpress - config apache
  include_tasks: apache.yml
  when: ansible_hostname == server2.name|string

- name: wordpress - flush handlers
  meta: flush_handlers

- name: wordpress - init wordpress
  include_tasks: cli.yml
  when: ansible_hostname == server2.name|string
