---

- name: Get dir stats
  stat:
    path: /var/lib/zabbix/
  register: zdir

- name: Make dir
  file:
    path: /var/lib/zabbix/
    state: directory
    owner: root
    group: root
    mode: 0775
  when: zdir.stat.isdir is not defined

- name: Test copy
  copy:
    src: "{{ item.src }}" 
    dest: "{{ item.dest }}"
    remote_src: yes
  with_items:
  - {src: '/share/zabbix/template_db_postgresql.conf',dest: '/etc/zabbix/zabbix_agentd.d/template_db_postgresql.conf'}
  - {src: '/share/zabbix/postgresql/',dest: '/var/lib/zabbix/postgresql/'}
