---

- name: apache - install php frontend
  apt:
    name: zabbix-frontend-php
    state: latest

- name: apache - copy apache config
  template:
    src: zabbix.conf
    dest: /etc/apache2/sites-available/zabbix.conf
    mode: 0644
    owner: root
    group: root

- name: apache - copy php config
  template:
    src: zabbix.conf.php
    dest: /etc/zabbix/web/zabbix.conf.php
    mode: 0644
    owner: root
    group: root

- name: apache - enable zabbix config
  lineinfile:
    path: /etc/apache2/sites-available/apache.conf
    insertafter: '^  # Service list'
    line: '  Include  /etc/apache2/sites-available/zabbix.conf'

- name: apache - reload
  systemd:
    name: apache2.service
    state: reloaded
