---

- name: db - add zabbix sql script
  apt:
    name: zabbix-sql-scripts
    state: latest

- name: db - create user
  become_user: postgres
  postgresql_user:
    name: "{{ db.zabbix.user }}"
    password: "{{ db.zabbix.pass }}"
    role_attr_flags: SUPERUSER

- name: db - create db
  become_user: postgres
  postgresql_db:
    name: "{{ db.zabbix.name }}"
    owner: "{{ db.zabbix.user }}"
    encoding: UTF-8

- name: db - grant privileges
  become_user: postgres
  postgresql_privs:
    db: "{{ db.zabbix.name }}"
    privs: ALL
    type: database
    role: "{{ db.zabbix.user }}"

- name: db - question
  pause:
    prompt: "Need to restore dump (y - yes / other - no)?"
    echo: yes
  register: zabbix_dump

- name: db - restore db
  become_user: postgres
  postgresql_db:
    name: "{{ db.zabbix.name }}"
    state: restore
    target: /usr/share/doc/zabbix-sql-scripts/postgresql/server.sql.gz
    target_opts: pg_restore
  when: zabbix_dump.user_input == 'y'

- name: db - user auth conf
  become_user: postgres
  postgresql_pg_hba:
    dest: /etc/postgresql/{{ db.ver }}/main/pg_hba.conf
    contype: host
    users: "{{ db.zabbix.user }}"
    databases: "{{ db.zabbix.name }}"
    source: "{{ vpn.gate }}/{{ vpn.prefix }}"
    method: md5

- name: db - reload postgres service
  systemd:
    name: postgresql.service
    state: reloaded
