---

- name: zabbix - add repozitory
  apt:
    deb: https://repo.zabbix.com/zabbix/6.0/ubuntu/pool/main/z/zabbix-release/zabbix-release_6.0-3+ubuntu20.04_all.deb

- name: zabbix - update cache
  apt:
    update_cache: yes

- name: zabbix - add sql script
  apt:
    name: zabbix-sql-scripts
    state: latest
  when: ansible_hostname == server3.name|string

- name: zabbix - config db
  import_tasks: db.yml
  vars:
    ansible_become_user: postgres
  when: ansible_hostname == server3.name|string

- name: zabbix - reload postgres service
  systemd:
    name: postgresql.service
    state: reloaded
  when: ansible_hostname == server3.name|string

- name: zabbix - setup server
  import_tasks: server.yml
  when: ansible_hostname == server1.name|string

- name: zabbix - setup agent
  import_tasks: agent.yml

- name: zabbix - config apache
  import_tasks: apache.yml
  when: ansible_hostname == server2.name|string
