---

- name: zabbix - add repozitory
  apt:
    deb: https://repo.zabbix.com/zabbix/5.0/ubuntu/pool/main/z/zabbix-release/zabbix-release_5.0-1+focal_all.deb
# https://repo.zabbix.com/zabbix/6.0/ubuntu/pool/main/z/zabbix-release/zabbix-release_6.0-3+ubuntu20.04_all.deb
  register: repolist_changed

- name: zabbix - update cache
  apt:
    update_cache: yes
  when: repolist_changed is changed

- name: zabbix - config db
  include_tasks: db.yml
  when: ansible_hostname == server3.name|string

- name: zabbix - setup server
  include_tasks: server.yml
  when: ansible_hostname == server1.name|string

- name: zabbix - setup agent
  include_tasks: agent.yml

- name: zabbix - config apache
  include_tasks: apache.yml
  when: ansible_hostname == server2.name|string

- name: zabbix - config monitoring
  include_tasks: db_monitoring.yml
  when: ansible_hostname == server3.name|string
