---

- name: zabbix - make source dir
  file:
    path: "{{ item }}"
    state: directory
    owner: root
    group: root
    mode: 0775
  with_items:
    - /var/lib/zabbix/
    - /tmp/zabbix

- name: zabbix - unzip zabbix.zip
  unarchive:
    src: /share/zabbix.zip
    dest: /tmp/zabbix
    owner: root
    group: root

- name: zabbix - copy source
  copy:
    src: "{{ item.src }}" 
    dest: "{{ item.dest }}"
    remote_src: yes
  with_items:
  - {src: '/tmp/zabbix/templates/db/postgresql/template_db_postgresql.conf', dest: '/etc/zabbix/zabbix_agentd.d/template_db_postgresql.conf'}
  - {src: '/tmp/zabbix/templates/db/postgresql/postgresql/', dest: '/var/lib/zabbix/postgresql/'}
