---

- name: apt - update cache
  apt:
    update_cache: yes

- name: apt - upgrade
  apt:
    upgrade: safe

- name: apt - install few packages
  apt:
    pkg:
    - net-tools
    - network-manager
    - tree
    - apt-transport-https
    - unzip
    - zip

- name: timezone - set timezone 
  timezone:
    name: Europe/Moscow

- name: vim & bash - configure
  include_tasks: useful.yml
