---

- name: apt - update cache
  apt:
    update_cache: yes

- name: apt - upgrade
  apt:
    upgrade: safe
  tags: useful

- name: apt - install few packages
  apt:
    pkg:
    - net-tools
    - network-manager
    - tree
    - apt-transport-https
    - unzip
    - zip

- name: timezone - set timezone 
  timezone:
    name: Europe/Moscow

- name: sshd - configure
  include_tasks: sshd.yml

- name: ufw - configure
  include_tasks: ufw.yml

- name: vim & bash - configure
  include_tasks: useful.yml
  tags: useful
