---

- name: Set permissions
  shell: "{{ item.shell }}"
  with_items:
  - {shell: 'chown -R {{ ansible_user }}:{{ ansible_user }} /share'}
  - {shell: 'find /share -type d -exec chmod 775 {} \;'}
  - {shell: 'find /share -type f -exec chmod 664 {} \;'}
