---

- name: ufw - allow outgoing trafic
  ufw:
    default: allow
    direction: outgoing

- name: ufw - deny incoming trafic
  ufw:
    default: deny
    direction: incoming

- name: ufw - allow ssh on {{ server2.name }} 
  ufw:
    rule: allow
    name: OpenSSH
  when: ansible_hostname == '{{ server2.name }}'

- name: ufw - allow ssh on other servers
  ufw:
    rule: allow
    name: OpenSSH
    interface: "{{ default_ipv4.interface }}"
  when: ansible_hostname != '{{ server2.name }}'

- name: ufw - enable
  ufw:
    state: enabled
