---

- name: vim - configure
  template:
    src: vimrc.local
    dest: /etc/vim/vimrc.local
    owner: root
    group: root
    mode: "0644"
    backup: yes

- name: bashrc - configure
  lineinfile:
    line: source .bashrc.local
    path: /home/{{ ansible_user }}/.bashrc
    backup: yes

- name: bashrc - add local
  template:
    src: bashrc.local
    dest: /home/{{ ansible_user }}/.bashrc.local
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: "0600"
    backup: yes
