---

- name: dbms - add postgresql repository key
  apt_key:
    id: B97B0AFCAA1A47F044F244A07FCC7D46ACCC4CF8
    # curl -sL https://www.postgresql.org/media/keys/ACCC4CF8.asc | tee | gpg --keyid-format long
    url: https://www.postgresql.org/media/keys/ACCC4CF8.asc
    state: present

- name: dbms - add postgresql repository list
  template:
    src: pgdg.list 
    dest: /etc/apt/sources.list.d/pgdg.list
    owner: root
    group: root
    mode: 0644

- name: dbms - update apt cache
  apt:
    update_cache: yes

- name: dbms - install postgrsql
  apt:
    pkg:
    - postgresql-{{ db.ver }}
    - postgresql-contrib-{{ db.ver }}

- name: dbms - install few pkg
  apt:
    pkg:
    - libpq-dev
    - acl

- name: dbms - install python lib
  pip:
    name: psycopg2
    state: latest

- name: dbms - stop and disable postgresql service
  systemd:
    name: postgresql.service
    enabled: no
    state: stopped

- name: dbms - add cron job 
  cron:
    name: start postgresql after reboot server
    special_time: reboot
    job: "/bin/sleep 30 && /bin/systemctl start postgresql.service"

- name: dbms - listen addresses
  replace:
    path: /etc/postgresql/{{ db.ver }}/main/postgresql.conf
    regexp: "^#listen_addresses = 'localhost"
    replace: "listen_addresses = '{{ ansible_facts.tun0.ipv4.address }}"
    backup: yes

- name: dbms - add ufw rule
  ufw:
    rule: allow
    port: 5432
    direction: in
    interface: "{{ ansible_facts.tun0.device }}"
    from_ip: '{{ vpn.gate }}/{{ vpn.prefix }}'
  register: ufw_changed

- name: dbms - reload ufw
  ufw:
    state: reloaded
  when: ufw_changed is changed

- name: dbms - start postgresql service
  systemd:
    name: postgresql.service
    state: started
