---

- name: apache - copy config
  template:
    src: wordpress.conf
    dest: /etc/apache2/sites-available/wordpress.conf
    mode: 0640
    owner: root
    group: www-data
  notify: handlers - reload apache service

- name: apache - enable wordpress config
  lineinfile:
    path: /etc/apache2/sites-available/apache.conf
    insertafter: '^  # Service list'
    line: '  Include  /etc/apache2/sites-available/wordpress.conf'
  notify: handlers - reload apache service
