---

- name: install - install bind
  apt:
    name: bind9
    state: latest

- name: install - start and enable service
  systemd:
    name: named.service
    enabled: yes
    state: started

- name: install - make zones dir
  file:
    path: "{{ item.path }}"
    state: directory
    owner: root
    group: bind
    mode: 0750
  with_items:
    - {path: '/etc/bind/myzones/{{ domain.second }}'}
    - {path: '/etc/bind/myzones/local'}

- name: install - config bind
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: root
    group: bind
    mode: 0640
  with_items:
    - {src: 'local.db', dest: '/etc/bind/myzones/local/local.db'}
    - {src: 'public.db', dest: '/etc/bind/myzones/{{ domain.second }}/{{ domain.second }}.db'}
    - {src: 'named.conf.local', dest: '/etc/bind/named.conf.local'}
    - {src: 'named.conf.options', dest: '/etc/bind/named.conf.options'}
  notify: handlers - reload bind

- name: install - add ufw bind rule
  ufw:
    rule: allow
    name: Bind9
  notify: handlers - reload ufw

- name: install - flush handlers
  meta: flush_handlers
