---

- name: install - install bind9
  apt:
    name: bind9
    state: latest

- name: install - stop and enable service
  systemd:
    name: named.service
    enabled: yes
    state: stopped

- name: install - make zones dir
  file:
    path: "{{ item.path }}"
    state: directory
    mode: 0755
  with_items:
    - {path: '/etc/bind/myzones/{{ domain.second }}'}
    - {path: '/etc/bind/myzones/local'}

- name: install - config bind
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: 0644
  with_items:
    - {src: 'local.db', dest: '/etc/bind/myzones/local/local.db'}
    - {src: 'public.db', dest: '/etc/bind/myzones/{{ domain.second }}/{{ domain.second }}.db'}
    - {src: 'named.conf.local', dest: '/etc/bind/named.conf.local'}
    - {src: 'named.conf.options', dest: '/etc/bind/named.conf.options'}

- name: install - add ufw bind rule
  ufw:
    rule: allow
    name: Bind9
  register: ufw_changed

- name: install - reload ufw
  ufw:
    state: reloaded
  when: ufw_changed is changed

- name: install - start bind service
  systemd:
    name: named.service
    state: started
