---

- name: bind - install and config bind9
  import_tasks: install.yml
  when: ansible_hostname == server2.name|string

- name: bind - config systemd-resolved
  template:
    src: resolved.conf
    dest: "/etc/systemd/resolved.conf"
    mode: 0644
  notify:
    - handlers - restarted systemd-resolved

- name: bind - add cron job
  cron:
    name: restart systemd-resolved after reboot server
    special_time: reboot
    job: "/bin/sleep 30 && /bin/systemctl restart systemd-resolved.service"
