---

- name: share - create share dir
  file:
    path: /share
    state: directory
    owner: root
    group: root
    mode: 0775

- name: share - make bash config dir
  file:
    path: /share/bash_conf/
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: 0750

- name: share - prepare bash config
  file:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: 0640
    state: link
    force: yes
  with_items:
    - {src: '/ansible/roles/init/templates/server1', dest: '/share/bash_conf/{{ server1.name }}'}
    - {src: '/ansible/roles/init/templates/server2', dest: '/share/bash_conf/{{ server2.name }}'}
    - {src: '/ansible/roles/init/templates/server3', dest: '/share/bash_conf/{{ server3.name }}'}

- name: share - make openvpn config dir
  file:
    path: /share/vpn_conf/
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: 0750

- name: share - prepare openvpn config
  file:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: 0640
    state: link
    force: yes
  with_items:
    - {src: '/ansible/roles/openvpn/templates/server1', dest: '/share/vpn_conf/{{ server1.name }}'}
    - {src: '/ansible/roles/openvpn/templates/server2', dest: '/share/vpn_conf/{{ server2.name }}'}
    - {src: '/ansible/roles/openvpn/templates/server3', dest: '/share/vpn_conf/{{ server3.name }}'}
    - {src: '/ansible/roles/openvpn/templates/vpn-server2', dest: '/share/vpn_conf/vpn-{{ server2.name }}'}
    - {src: '/ansible/roles/openvpn/templates/vpn-server3', dest: '/share/vpn_conf/vpn-{{ server3.name }}'}

- name: share - make beats config dir
  file:
    path: /share/beats_conf/
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: 0750

- name: share - prepare bearts config
  file:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: 0640
    state: link
    force: yes
  with_items:
    - {src: '/ansible/roles/beats/templates/server1', dest: '/share/beats_conf/{{ server1.name }}'}
    - {src: '/ansible/roles/beats/templates/server2', dest: '/share/beats_conf/{{ server2.name }}'}

- name: share - download easy-rsa
  get_url:
    url: https://github.com/OpenVPN/easy-rsa/archive/refs/heads/release/3.0.zip
    dest: /share/easy_rsa.zip
    owner: root
    group: root
    mode: 0664

- name: share - unzip easy_rsa.zip
  unarchive:
    src: /share/easy_rsa.zip
    dest: /tmp/
    list_files: yes
    remote_src: yes
  register: unzip

- name: share - copy easy_rsa dir
  copy:
    src: /tmp/{{ unzip.files[0] }}/easyrsa3/
    dest: /share/easy_rsa
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    remote_src: yes

- name: easy_rsa - remove easy_rsa tmp dir
  file:
    path: "{{ item }}"
    state: absent
  loop:
    - /tmp/{{ unzip.files[0] }}

- name: share - download wordpress
  get_url:
    url: https://ru.wordpress.org/latest-ru_RU.zip
    dest: /share/wordpress.zip
    mode: 0644
    owner: root
    group: root

- name: share - download pg4wp
  get_url:
    url: https://github.com/kevinoid/postgresql-for-wordpress/archive/refs/heads/wordpress4-compat.zip
    dest: /share/pg4wp.zip
    mode: 0644
    owner: root
    group: root

- name: share - download roundcube
  get_url:
    url: https://github.com/roundcube/roundcubemail/releases/download/1.5.2/roundcubemail-1.5.2-complete.tar.gz
    dest: /share/roundcube.tar.gz
    mode: 0644
    owner: root
    group: root

- name: share - download demo dump
  get_url:
    url: https://edu.postgrespro.ru/demo-small.zip
    dest: /share/demo.zip
    mode: 0644
    owner: root
    group: root

- name: share - download zabbix sourse
  get_url:
    url: https://git.zabbix.com/rest/api/latest/projects/ZBX/repos/zabbix/archive?at=refs%2Fheads%2Frelease%2F6.0&format=zip
    dest: /share/zabbix.zip
    mode: 0644
    owner: root
    group: root
