---

- name: share - create share dir
  file:
    path: /share
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: 0755

- name: share - make bash config dir
  file:
    path: /share/bash_conf/
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: 0755

- name: share - prepare bash config
  file:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: 0640
    state: link
  with_items:
    - {src: '/ansible/roles/init/templates/server1', dest: '/share/bash_conf/{{ server1.name }}'}
    - {src: '/ansible/roles/init/templates/server2', dest: '/share/bash_conf/{{ server2.name }}'}
    - {src: '/ansible/roles/init/templates/server3', dest: '/share/bash_conf/{{ server3.name }}'}

- name: share - make openvpn config dir
  file:
    path: /share/vpn_conf/
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: 0750

- name: share - prepare openvpn config
  file:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: 0640
    state: link
  with_items:
    - {src: '/ansible/roles/openvpn/templates/server1', dest: '/share/vpn_conf/{{ server1.name }}'}
    - {src: '/ansible/roles/openvpn/templates/server2', dest: '/share/vpn_conf/{{ server2.name }}'}
    - {src: '/ansible/roles/openvpn/templates/server3', dest: '/share/vpn_conf/{{ server3.name }}'}
    - {src: '/ansible/roles/openvpn/templates/vpn-server2', dest: '/share/vpn_conf/vpn-{{ server2.name }}'}
    - {src: '/ansible/roles/openvpn/templates/vpn-server3', dest: '/share/vpn_conf/vpn-{{ server3.name }}'}

- name: share - make beats config dir
  file:
    path: /share/beats_conf/
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: 0755

- name: share - prepare beats config
  file:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: 0640
    state: link
  with_items:
    - {src: '/ansible/roles/beats/templates/server1', dest: '/share/beats_conf/{{ server1.name }}'}
    - {src: '/ansible/roles/beats/templates/server2', dest: '/share/beats_conf/{{ server2.name }}'}

- name: share - download easy-rsa
  get_url:
    url: https://github.com/OpenVPN/easy-rsa/archive/refs/heads/release/3.0.zip
    dest: /share/easy_rsa.zip
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: 0640

- name: share - unzip easy_rsa.zip
  unarchive:
    creates: /share/easy_rsa/pki/
    src: /share/easy_rsa.zip
    dest: /tmp/
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    remote_src: yes
    include: easy-rsa-release-3.0/easyrsa3/*

- name: share - copy easy_rsa dir
  copy:
    src: /tmp/easy-rsa-release-3.0/easyrsa3/
    dest: /share/easy_rsa
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    remote_src: yes
    force: no

- name: share - download wordpress
  get_url:
    url: https://ru.wordpress.org/latest-ru_RU.zip
    dest: /share/wordpress.zip
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: 0640

- name: share - download wp-cli
  get_url:
    url: https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar
    dest: /share/wp-cli.phar
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: 0750

- name: share - download pg4wp
  get_url:
    url: https://github.com/kevinoid/postgresql-for-wordpress/archive/refs/heads/wordpress4-compat.zip
    dest: /share/pg4wp.zip
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: 0640

- name: share - download roundcube
  get_url:
    url: https://github.com/roundcube/roundcubemail/releases/download/1.5.2/roundcubemail-1.5.2-complete.tar.gz
    dest: /share/roundcube.tar.gz
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: 0640

- name: share - download demo dump
  get_url:
    url: https://edu.postgrespro.ru/demo-small.zip
    dest: /share/demo.zip
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: 0640

- name: share - download zabbix sourse
  get_url:
    url: https://git.zabbix.com/rest/api/latest/projects/ZBX/repos/zabbix/archive?at=refs%2Fheads%2Frelease%2F6.0&format=zip
    dest: /share/zabbix.zip
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: 0640
