---

- name: handler_restart_postfix
  systemd:
    name: postfix.service
    enabled: yes
    state: restarted

- name: handler_restart_dovecot
  systemd:
    name: dovecot.service
    enabled: yes
    state: restarted
