---

- name: Config client
  template:
    src: "{{ ansible_hostname }}"
    dest: "/etc/openvpn/clientvpn.conf"
    mode: 0644

- name: Starti client
  systemd:
    daemon_reload: yes
    name: openvpn@clientvpn.service
    enabled: yes
    state: started
