---

- name: vpnclient - config client
  template:
    src: "{{ ansible_hostname }}"
    dest: /etc/openvpn/clientvpn.conf
    mode: 0644
    backup: yes

- name: vpnclient - start client
  systemd:
    daemon_reload: yes
    name: openvpn@clientvpn.service
    enabled: yes
    state: started
