---

- name: vpnclient - config client
  template:
    src: "{{ ansible_hostname }}"
    dest: /etc/openvpn/clientvpn.conf
    mode: 0644
    backup: yes

- name: vpnclient - start client
  systemd:
    daemon_reload: yes
    name: openvpn@clientvpn.service
    enabled: yes
    state: started
  register: client_started

- name: vpnclient - reload client
  systemd:
    name: openvpn@clientvpn.service
    state: restarted
  when: client_started is not changed

- name: vpnserver - add ssh ufw rule
  ufw:
    rule: allow
    proto: udp
    port: 22
    direction: in
    interface: tun0
  when: ansible_hostname != server2.name|string

- name: vpnserver - reloaded ufw
  ufw:
    state: reloaded
