---

- name: openvpn - install
  apt:
    name: openvpn
    state: latest

- name: openvpn - start
  systemd:
    name: openvpn.service
    enabled: yes
    state: started

- name: openvpn - config server
  import_tasks: server.yml
  when: ansible_hostname == server1.name|string

- name: openvpn - config clients
  import_tasks: client.yml
  when: ansible_hostname != server1.name|string
