---

- name: openvpn - install openvpn
  include_tasks: install.yml

- name: openvpn - config openvpn-server
  include_tasks: server.yml
  when: ansible_hostname == server1.name|string

- name: openvpn - config openvpn-clients
  import_tasks: client.yml
  when: ansible_hostname != server1.name|string

- name: openvpn - config ssh
  include_tasks: ssh.yml
