---

- name: Install OpenVPN
  apt:
    name: openvpn
    state: latest

- name: Start OpenVPN
  systemd:
    name: openvpn.service
    enabled: yes
    state: started

- name: Up OpenVPN server
  import_tasks: server.yml
  when: ansible_hostname == 'mk-server1'

- name: Up OpenVPN clients
  import_tasks: client.yml
  when: ansible_hostname != 'mk-server1'
