---

- name: openvpn - collect facts
  gather_facts:

- name: openvpn - install openvpn
  apt:
    name: openvpn
    state: latest

- name: openvpn - start openvpn service
  systemd:
    name: openvpn.service
    enabled: yes
    state: started

- name: openvpn - config openvpn-server
  include_tasks: server.yml
  when: ansible_hostname == server1.name|string

- name: openvpn - config openvpn-clients
  include_tasks: client.yml
  when: ansible_hostname != server1.name|string

- name: openvpn - config ssh
  include_tasks: ssh.yml
