---

- name: Make_source_dir
  ansible.builtin.file:
    path: "/etc/openvpn/ccd"
    state: "directory"
    mode: "0755"
  with_items:
  - {path: '/etc/openvpn/client.list',state: 'touch',mode: '0644'}
  - {path: '/etc/openvpn/ccd',state: 'directory',mode: '0755'}

- name: Get_client_list_stats
  stat:
    path: "/etc/openvpn/client.list"
  register: list

- name: Make_client_list
  ansible.builtin.file:
    path: "/etc/openvpn/client.list"
    state: "touch"
    mode: "0644"
  when: list.stat.isreg is not defined

- name: Config_server
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: 0600
  with_items:
  - {src: '{{ ansible_hostname }}',dest: '/etc/openvpn/servervpn.conf'}
  - {src: 'client1vpn',dest: '/etc/openvpn/ccd/client1vpn'}
  - {src: 'client2vpn',dest: '/etc/openvpn/ccd/client2vpn'}

- name: Start_server
  ansible.builtin.systemd:
    daemon_reload: "yes"
    name: "openvpn@servervpn.service"
    enabled: "yes"
    state: "started"
