---

- name: Make source
  file:
    path: "{{ item.path }}"
    state: "{{ item.state }}"
    mode: "{{ item.mode }}"
  with_items:
  - {path: '/etc/openvpn/client.list',state: 'touch',mode: '0644'}
  - {path: '/etc/openvpn/ccd',state: 'directory',mode: '0755'}

- name: Config server
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: 0600
  with_items:
  - {src: '{{ ansible_hostname }}',dest: '/etc/openvpn/servervpn.conf'}
  - {src: 'client1vpn',dest: '/etc/openvpn/ccd/client1vpn'}
  - {src: 'client2vpn',dest: '/etc/openvpn/ccd/client2vpn'}

- name: Start server
  systemd:
    daemon_reload: yes
    name: openvpn@servervpn.service
    enabled: yes
    state: started
