---

- name: server - make server source
  file:
    path: "{{ item.path }}"
    state: "{{ item.state }}"
    mode: "{{ item.mode }}"
  with_items:
  - {path: '/etc/openvpn/client.list', state: 'touch', mode: '0640'}
  - {path: '/etc/openvpn/ccd', state: 'directory' , mode: '0750'}
  - {path: '/etc/openvpn/cert', state: 'directory' , mode: '0750'}

- name: server - make client config file
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: 0640
    backup: yes
  with_items:
  - {src: '/share/vpn_conf/vpn-{{ server2.name }}', dest: '/etc/openvpn/ccd/vpn-{{ server2.name }}'}
  - {src: '/share/vpn_conf/vpn-{{ server3.name }}', dest: '/etc/openvpn/ccd/vpn-{{ server3.name }}'}

- name: server - copy cert
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: root
    group: root
    mode: 0600
  with_items:
    - {src: '/share/easy_rsa/pki/ca.crt', dest: '/etc/openvpn/cert/ca.crt'}
    - {src: '/share/easy_rsa/pki/dh.pem', dest: '/etc/openvpn/cert/dh.pem'}
    - {src: '/share/easy_rsa/pki/issued/vpn-{{ ansible_hostname }}.crt', dest: '/etc/openvpn/cert/vpn-{{ ansible_hostname }}.crt'}
    - {src: '/share/easy_rsa/pki/private/vpn-{{ ansible_hostname }}.key', dest: '/etc/openvpn/cert/vpn-{{ server1.name }}.key'}

- name: server - config server
  template:
    src: /share/vpn_conf/{{ ansible_hostname }}
    dest: /etc/openvpn/vpn-{{ ansible_hostname }}.conf
    mode: 0640
    backup: yes

- name: server - start openvpn server service
  systemd:
    daemon_reload: yes
    name: openvpn@vpn-{{ ansible_hostname }}.service
    enabled: yes
    state: started
  register: server_started

- name: server - reload openvpn server service
  systemd:
    name: openvpn@vpn-{{ ansible_hostname }}.service
    state: restarted
  when:  server_started is not changed
